"""payment

Revision ID: 18cf02b9f446
Revises: c077690258d8
Create Date: 2025-11-14 00:04:44.444276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18cf02b9f446'
down_revision: Union[str, None] = 'c077690258d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define Enum type for reuse
subscription_status_enum = sa.Enum('trial', 'trial_expired', 'active', 'expired', name='subscriptionstatusenum')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create the ENUM type before altering the column
    subscription_status_enum.create(op.get_bind())
    
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               type_=subscription_status_enum,
               existing_nullable=False,
               postgresql_using='status::subscriptionstatusenum')

    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'username')
    op.alter_column('subscriptions', 'status',
               existing_type=subscription_status_enum,
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('payments')
    
    # Drop the ENUM type after it's no longer in use
    subscription_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
