"""fix

Revision ID: 205aecf387e0
Revises: None
Create Date: 2025-10-13 23:07:15.618227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '205aecf387e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('equipment_type', sa.Enum('gym', 'bodyweight', name='equipmenttypeenum'), nullable=False))
    op.create_unique_constraint(None, 'exercises', ['name'])
    op.alter_column('workout_exercises', 'reps',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('workout_exercises', 'weight')
    op.drop_column('workout_exercises', 'rest_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_exercises', sa.Column('rest_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workout_exercises', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('workout_exercises', 'reps',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'exercises', type_='unique')
    op.drop_column('exercises', 'equipment_type')
    # ### end Alembic commands ###
