"""fix

Revision ID: 220176332a45
Revises: 205aecf387e0
Create Date: 2025-10-13 23:47:11.214749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220176332a45'
down_revision: Union[str, None] = '205aecf387e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exercises_name_key'), 'exercises', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('exercises_name_key'), 'exercises', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
