"""fix

Revision ID: 5d130e19f055
Revises: 6e10db5708d2
Create Date: 2025-10-18 15:22:38.781597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d130e19f055'
down_revision: Union[str, None] = '6e10db5708d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('warm_up', sa.String(), nullable=True))
    op.add_column('workouts', sa.Column('cool_down', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'cool_down')
    op.drop_column('workouts', 'warm_up')
    # ### end Alembic commands ###
