"""add video_id, gif_id

Revision ID: 682dc2da9d3d
Revises: d0738c9bddb9
Create Date: 2025-10-29 18:59:25.528418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682dc2da9d3d'
down_revision: Union[str, None] = 'd0738c9bddb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('video_id', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('gif_id', sa.String(), nullable=True))
    op.drop_column('exercises', 'image_url')
    op.drop_column('exercises', 'video_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('video_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('exercises', 'gif_id')
    op.drop_column('exercises', 'video_id')
    # ### end Alembic commands ###
