"""fix

Revision ID: 6c2f8457f879
Revises: 220176332a45
Create Date: 2025-10-16 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2f8457f879'
down_revision: Union[str, None] = '220176332a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE workoutscheduledayenum RENAME TO workoutscheduledayenum_old;")
    op.execute("CREATE TYPE workoutscheduledayenum AS ENUM('понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье');")
    op.execute("""
        ALTER TABLE workout_schedules
        ALTER COLUMN day TYPE workoutscheduledayenum
        USING day::text::workoutscheduledayenum;
    """)
    op.execute("DROP TYPE workoutscheduledayenum_old;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE workout_schedules
        ALTER COLUMN day TYPE VARCHAR;
    """)
    op.execute("DROP TYPE workoutscheduledayenum;")
    op.execute("CREATE TYPE workoutscheduledayenum AS ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday');")
    op.execute("""
        ALTER TABLE workout_schedules
        ALTER COLUMN day TYPE workoutscheduledayenum
        USING day::VARCHAR::workoutscheduledayenum;
    """)
    # ### end Alembic commands ###
