"""fix

Revision ID: 6e10db5708d2
Revises: d9bb202016a9
Create Date: 2025-10-18 14:48:42.485685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e10db5708d2'
down_revision: Union[str, None] = 'd9bb202016a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_training_week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_training_week')
    # ### end Alembic commands ###
