"""initial

Revision ID: 7c9ee4151af1
Revises: None
Create Date: 2025-10-30 02:10:39.577336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9ee4151af1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('muscle_groups', sa.String(), nullable=True),
    sa.Column('equipment_type', sa.Enum('gym', 'bodyweight', name='equipmenttypeenum'), nullable=False),
    sa.Column('video_id', sa.String(), nullable=True),
    sa.Column('gif_id', sa.String(), nullable=True),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='genderenum'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('goal', sa.Enum('mass_gain', 'weight_loss', 'maintenance', name='goalenum'), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('fitness_level', sa.Enum('beginner', 'intermediate', 'advanced', name='fitnesslevelenum'), nullable=True),
    sa.Column('workout_frequency', sa.Integer(), nullable=True),
    sa.Column('current_training_week', sa.Integer(), nullable=True),
    sa.Column('equipment_type', sa.Enum('gym', 'bodyweight', name='equipmenttypeenum'), nullable=True),
    sa.Column('trainer_style', sa.Enum('goggins', 'schwarzenegger', 'coleman', name='trainerstyleenum'), nullable=True),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('workout_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье', name='workoutscheduledayenum'), nullable=False),
    sa.Column('notification_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planned_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'completed', 'skipped', 'sent', name='workoutstatusenum'), nullable=False),
    sa.Column('warm_up', sa.String(), nullable=True),
    sa.Column('cool_down', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('workout_schedules')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
