"""add_trainer_style_to_user

Revision ID: a9226043dcf1
Revises: 5d130e19f055
Create Date: 2025-10-28 10:30:14.139551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9226043dcf1'
down_revision: Union[str, None] = '5d130e19f055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем enum тип
    op.execute("CREATE TYPE trainerstyleenum AS ENUM('goggins', 'schwarzenegger', 'coleman');")
    # Добавляем колонку с этим типом
    op.add_column('users', sa.Column('trainer_style', sa.Enum('goggins', 'schwarzenegger', 'coleman', name='trainerstyleenum', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем колонку
    op.drop_column('users', 'trainer_style')
    # Удаляем enum тип
    op.execute("DROP TYPE trainerstyleenum;")
    # ### end Alembic commands ###
